version: "2"
services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodejs_app
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - '3333:3306'
  node:
    build: ./node
    command: "npm run dev"
  nginx:
    build: ./nginx
    ports:
      - 8080:80
  ssh:
    image: 'biftin/ssh:latest'
    environment:
      SSH_PASS: 'u7H:HQ9;Gv:(W]YN'
    ports:
      - '2222:22'
    volumes_from:
      - 'node'
